version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash build
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
